

game.AddParticles("particles/MHA_Dureks.pcf")
game.AddParticles("particles/ryuko_pfx.pcf")
PrecacheParticleSystem("{2}Torn")
PrecacheParticleSystem("Explosion_fire_Little")
PrecacheParticleSystem("ExplosionCore_MidAir")
PrecacheParticleSystem("ExplosionCore_Wall_Litle")
PrecacheParticleSystem("cinefx_goldrush_hugedustup")
PrecacheParticleSystem("Advisor_Room_Debris")
PrecacheParticleSystem("aurora_02b")
PrecacheParticleSystem("demon_un")
PrecacheParticleSystem("Explosion_bubbles")
PrecacheParticleSystem("")
PrecacheParticleSystem("")
PrecacheParticleSystem("")
PrecacheParticleSystem("")