CreateClientConVar( "TouchesBind1", 15, true, true )
CreateClientConVar( "TouchesBind2", 28, true, true )
CreateClientConVar( "TouchesBind3", 15, true, true )
CreateClientConVar( "TouchesBind4", 28, true, true )
CreateClientConVar( "TouchesBind5", 15, true, true )
CreateClientConVar( "TouchesBind6", 28, true, true )
CreateClientConVar( "TouchesBind7", 15, true, true )
CreateClientConVar( "TouchesBind8", 28, true, true )


hook.Add( "PopulateToolMenu", "Magie:Touches:BindsConfig", function()
		spawnmenu.AddToolMenuOption( "Magie", "AntiMagie", "ConfigBinds", "#Binds", "", "", function( panel )
        panel:ClearControls()
            local un = vgui.Create("DBinder", panel)
                un:SetPos(175, 40)
                un:SetSize(100,45)
                un:SetConVar("TouchesBind1")
				
			local unt = vgui.Create("DLabel", panel)
                unt:SetPos(35, 50)
                unt:SetSize(100,30)
                unt:SetText("Technique 1 :")
                unt:SetTextColor(Color(0, 0, 0, 255) )
				
			local deu = vgui.Create("DBinder", panel)
                deu:SetPos(175, 40 + 70)
                deu:SetSize(100,45)
                deu:SetConVar("TouchesBind2")
				
			local deut = vgui.Create("DLabel", panel)
                deut:SetPos(35, 50 + 70)
                deut:SetSize(100,30)
                deut:SetText("Technique 2 :")
                deut:SetTextColor(Color(0, 0, 0, 255) )
				
			local troi = vgui.Create("DBinder", panel)
                troi:SetPos(175, 40 + 70+70)
                troi:SetSize(100,45)
                troi:SetConVar("TouchesBind3")
				
			local troit = vgui.Create("DLabel", panel)
                troit:SetPos(35, 50 + 70+70)
                troit:SetSize(100,30)
                troit:SetText("Technique 3 :")
                troit:SetTextColor(Color(0, 0, 0, 255) )

            local quatre = vgui.Create("DBinder", panel)
                quatre:SetPos(175, 40 + 70+70+70)
                quatre:SetSize(100,45)
                quatre:SetConVar("TouchesBind4")
				
			local quatret = vgui.Create("DLabel", panel)
                quatret:SetPos(35, 50 + 70+70+70)
                quatret:SetSize(100,30)
                quatret:SetText("Technique 4 :")
                quatret:SetTextColor(Color(0, 0, 0, 255) )
        end)
        spawnmenu.AddToolMenuOption( "Magie", "Tenebre", "ConfigBinds2", "#Binds", "", "", function( panel )
            panel:ClearControls()
                local un = vgui.Create("DBinder", panel)
                    un:SetPos(175, 40 )
                    un:SetSize(100,45)
                    un:SetConVar("TouchesBind5")
                    
                local unt = vgui.Create("DLabel", panel)
                    unt:SetPos(35, 50)
                    unt:SetSize(100,30)
                    unt:SetText("Technique 1 :")
                    unt:SetTextColor(Color(0, 0, 0, 255) )
                    
                local deu = vgui.Create("DBinder", panel)
                    deu:SetPos(175, 40 + 70)
                    deu:SetSize(100,45)
                    deu:SetConVar("TouchesBind6")
                    
                local deut = vgui.Create("DLabel", panel)
                    deut:SetPos(35, 50 + 70)
                    deut:SetSize(100,30)
                    deut:SetText("Technique 2 :")
                    deut:SetTextColor(Color(0, 0, 0, 255) )
            end)
            spawnmenu.AddToolMenuOption( "Magie", "Vent", "ConfigBinds33", "#Binds", "", "", function( panel )
                panel:ClearControls()
                    local un = vgui.Create("DBinder", panel)
                        un:SetPos(175, 40 )
                        un:SetSize(100,45)
                        un:SetConVar("TouchesBind7")
                        
                    local unt = vgui.Create("DLabel", panel)
                        unt:SetPos(35, 50)
                        unt:SetSize(100,30)
                        unt:SetText("Technique 1 :")
                        unt:SetTextColor(Color(0, 0, 0, 255) )
                        
                    local deu = vgui.Create("DBinder", panel)
                        deu:SetPos(175, 40 + 70)
                        deu:SetSize(100,45)
                        deu:SetConVar("TouchesBind8")
                        
                    local deut = vgui.Create("DLabel", panel)
                        deut:SetPos(35, 50 + 70)
                        deut:SetSize(100,30)
                        deut:SetText("Technique 2 :")
                        deut:SetTextColor(Color(0, 0, 0, 255) )
                end)
                spawnmenu.AddToolMenuOption( "Magie", "Berserker", "ConfigBinds", "#Binds", "", "", function( panel )
                    panel:ClearControls()
                        local un = vgui.Create("DBinder", panel)
                            un:SetPos(175, 40)
                            un:SetSize(100,45)
                            un:SetConVar("TouchesBind1")
                            
                        local unt = vgui.Create("DLabel", panel)
                            unt:SetPos(35, 50)
                            unt:SetSize(100,30)
                            unt:SetText("Technique 1 :")
                            unt:SetTextColor(Color(0, 0, 0, 255) )
                            
                        local deu = vgui.Create("DBinder", panel)
                            deu:SetPos(175, 40 + 70)
                            deu:SetSize(100,45)
                            deu:SetConVar("TouchesBind2")
                            
                        local deut = vgui.Create("DLabel", panel)
                            deut:SetPos(35, 50 + 70)
                            deut:SetSize(100,30)
                            deut:SetText("Technique 2 :")
                            deut:SetTextColor(Color(0, 0, 0, 255) )
                            
                        local troi = vgui.Create("DBinder", panel)
                            troi:SetPos(175, 40 + 70+70)
                            troi:SetSize(100,45)
                            troi:SetConVar("TouchesBind3")
                            
                        local troit = vgui.Create("DLabel", panel)
                            troit:SetPos(35, 50 + 70+70)
                            troit:SetSize(100,30)
                            troit:SetText("Technique 3 :")
                            troit:SetTextColor(Color(0, 0, 0, 255) )
            
                        local quatre = vgui.Create("DBinder", panel)
                            quatre:SetPos(175, 40 + 70+70+70)
                            quatre:SetSize(100,45)
                            quatre:SetConVar("TouchesBind4")
                            
                        local quatret = vgui.Create("DLabel", panel)
                            quatret:SetPos(35, 50 + 70+70+70)
                            quatret:SetSize(100,30)
                            quatret:SetText("Technique 4 :")
                            quatret:SetTextColor(Color(0, 0, 0, 255) )
                    end)

end)